### ISSUE TITLE
Smudge error: This repository is over its data quota.

### ISSUE THREAD

**Issue by fhestvang** [mollerhoj/Scandinavian-ULMFiT#7]
Hi @mollerhoj,

Thanks a ton for this ressource! 

Could you provide another access to the files than git lfs? As stated in the title there, it is not possible to download the files unless: "Account responsible for LFS bandwidth should purchase more data packs to restore access".

Best,
Frederik.

**Comment by R4ZZ3** [comment]
I was having same problem. Ended up loading with:
python -m wget <filepath>

**Comment by R4ZZ3** [comment]
Hi @mollerhoj 

I am having same the same issue as @fhestvang 
It would be really helpful to get access to these files.

Sincerely,
Rasmus

**Comment by fhestvang** [comment]
@mollerhoj has been extremely quick and kind and added download links in the readme. 👍
